name: Coffee
on:
  schedule:
  - cron: "0,15,30,45 ? * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Give coffee
        run: |
          wget ${{ secret.URL_LIST }} -O this.txt
          wget -i this.txt -O-
